slurms:
    - &one_sbatch
        slurm: "{SLURM}/one.sbatch"
        exports: ["python", "args"]
    - &many_sbatch
        slurm: "{SLURM}/many.sbatch"
        exports: ["python", "args"]
inputs:
    - &2017-08-28_soma
        LOG: "{HOME}/logging/2017-08-28"
        HD_IMG: "{COX_DATA}/test_sample/image.h5"
        HD_IDS: "{COX_DATA}/test_sample/segmentation.h5"
        Z_RUNS: 30
    - &2017-08-23_88_88_14
        LOG: "{HOME}/logging/2017-08-23"
        IMG_OFFSET: "-z 14:1728 -y 0:12288 -x 0:12288"
        BOSS_IMG: "{LEEK}/dropbox/25k_201610_dataset_em.json"
        BOSS_IDS: "{AUGUST_100}/88_88_14/boss/final-segmentation/boss.json"
        Z_RUNS: 30
    - &2017-09-16_preseg
        LOG: "{HOME}/logging/2017-09-16"
        PNG_IMG: "/n/coxfs01/data/JWR15_09_16_17_initial_preseg/grayscale_maps_cropped"
        HD_IDS: "/n/coxfs01/data/JWR15_09_16_17_initial_preseg/JWR-48K-1000-wshed.h5"
        Z_RUNS: 10
tasks:
    - &boss2mojo_img
        <<: *many_sbatch
        python: "{PYTHON}/conversion/boss2mojo.py"
        args: "{BOSS_IMG} -o {MOJO_PATH} -s {SCALE} {IMG_OFFSET}"
        logs: "{LOG}/boss2mojo_img"
        runs: "{Z_RUNS}"
    - &boss2mojo_ids
        <<: *many_sbatch
        python: "{PYTHON}/conversion/boss2mojo.py"
        args: "{BOSS_IDS} -o {MOJO_PATH} -s {SCALE}"
        logs: "{LOG}/boss2mojo_ids"
        runs: "{Z_RUNS}"
    - &boss2stack_img
        <<: *many_sbatch
        python: "{PYTHON}/conversion/boss2stack.py"
        args: "{BOSS_IMG} -o {JPG_IMG} -s {SCALE} -f {IMG_FMT} {IMG_OFFSET}"
        logs: "{LOG}/boss2stack_img"
        runs: "{Z_RUNS}"
    - &boss2stack_ids
        <<: *many_sbatch
        python: "{PYTHON}/conversion/boss2stack.py"
        args: "{BOSS_IDS} -o {PNG_IDS} -s {SCALE} -f {IDS_FMT}"
        logs: "{LOG}/boss2stack_ids"
        runs: "{Z_RUNS}"
    - &hd2mojo_img
        <<: *many_sbatch
        python: "{PYTHON}/conversion/hd2mojo.py"
        args: "{HD_IMG} {MOJO_PATH}"
        logs: "{LOG}/hd2mojo_img"
        runs: "{Z_RUNS}"
    - &hd2mojo_ids
        <<: *many_sbatch
        python: "{PYTHON}/conversion/hd2mojo.py"
        args: "{HD_IDS} {MOJO_PATH}"
        logs: "{LOG}/hd2mojo_ids"
        runs: "{Z_RUNS}"
    - &db4mojo
        <<: *one_sbatch
        python: "{PYTHON}/conversion/db4mojo.py"
        logs: "{LOG}/db4mojo"
        args: "{MOJO_PATH}"
    - &sides_z
        <<: *one_sbatch
        python: "{PYTHON}/scripts/sides.py"
        args: "{PNG_PATH} {HD_IMG} {HD_IDS} -i {ID} -o 0.25 -a z -z 5"
        logs: "{LOG}/z5_id-{ID}"
    - &png2hd_img
        <<: *one_sbatch
        python: "{PYTHON}/conversion/png2hd.py"
        args: "{PNG_IMG} {HD_IMG}"
        logs: "{LOG}/png2hd_img"
#####
# Actions run tasks on inputs
#####
actions:
    - &mojo_tasks
        tasks:
            - <<: *boss2mojo_ids
            - <<: *boss2mojo_img
    - &mojo_db_tasks
        tasks:
            - <<: *db4mojo
              needs:
                - <<: *boss2mojo_ids
            - <<: *boss2mojo_img
    - &mojo_50um_2017-10-31
        <<: *mojo_tasks
        inputs:
            <<: *2017-08-23_88_88_14
            MOJO_PATH: "{HOME}/mojo/2017_08_23/1_1_1/88_88_14/mojo/"
            SCALE: "0:0:0"
        
#####
# Set the main action
#####
main:
    <<: *mojo_50um_2017-10-31
    constants:
        AUGUST_100: "/n/coxfs01/leek/results/2017-08-23_100um_cube"
        HOME: "/n/coxfs01/thejohnhoffer"
        COX_DATA: "/n/coxfs01/data"
        LEEK: "/n/coxfs01/leek"
        PYTHON: "../PYTHON"
        SLURM: "../SLURM"
