slurms:
    - &one_sbatch
        slurm: "{SLURM}/one.sbatch"
        exports: ["python", "args"]
    - &many_sbatch
        slurm: "{SLURM}/many.sbatch"
        exports: ["python", "args"]
inputs:
    - &2017-08-28_soma
        LOG: "{HOME}/logging/2017-08-28"
        IN_IMG: "{COX_DATA}/test_sample/image.h5"
        IN_IDS: "{COX_DATA}/test_sample/segmentation.h5"
tasks:
    - &hd2mojo_img
        <<: *many_sbatch
        python: "{PYTHON}/conversion/hd2mojo.py"
        args: "{IN_IMG} {OUT_PATH}"
        logs: "{LOG}/hd2mojo_img"
        runs: 30
    - &hd2mojo_ids
        <<: *many_sbatch
        python: "{PYTHON}/conversion/hd2mojo.py"
        args: "{IN_IDS} {OUT_PATH}"
        logs: "{LOG}/hd2mojo_ids"
        runs: 30
    - &db4mojo
        <<: *one_sbatch
        python: "{PYTHON}/conversion/db4mojo.py"
        logs: "{LOG}/db4mojo"
        args: "{OUT_PATH}"
    - &sides_z
        <<: *one_sbatch
        python: "{PYTHON}/scripts/sides.py"
        args: "{OUT_PATH} {IN_IMG} {IN_IDS} -i {ID} -o 0.25 -a z -z 5"
        logs: "{LOG}/z5_id-{ID}"
#####
# Actions run scripts on inputs
#####
actions:
    - &full_2017-09-14
        inputs:
            <<: *2017-08-28_soma
            OUT_PATH: "{HOME}/mojo/2017_08_28/full_v0/mojo"
        tasks:
            - <<: *db4mojo
              needs:
                - <<: *hd2mojo_ids
            - <<: *hd2mojo_img
    - &slice_2017-09-07
        inputs:
            <<: *2017-08-28_soma
            OUT_PATH: "{HOME}/R0/render/2017-08-28/"
            ID: 58146
        tasks:
            - <<: *sides_z
#####
# Set the main action
#####
main:
    <<: *full_2017-09-14
    constants:
        HOME: "/n/coxfs01/thejohnhoffer"
        COX_DATA: "/n/coxfs01/data"
        PYTHON: "../PYTHON"
        SLURM: "../SLURM"
