# slyml.py v2.1
#
del-logs: &del-logs
    Bash: true
    Exports: [args]
    Slurm: ./SLURM/bash/one.sbatch
    args: 'rm {LOG}*'
########
# For blender
del-blend: &del-blend
    <<: *del-logs
    args: 'rm {BLEND}*'
light: &light
    Slurm: ./SLURM/blender/one.sbatch
    python: ./PYTHON/BLENDER/lights.py
    args: "-b {BLEND}"
block-0: &block-0
    Slurm: ./SLURM/blender/one.sbatch
    python: ./PYTHON/BLENDER/import.py
    args: "{OUT}/stl {STL_FILES} -b {BLEND} {BLOCK}"
    Inputs:
        STL_FILES: "-f %d/*.stl -l {ID-A}" 
        BLOCK: "--vox={XYZ_VOX} --VOL=50:50:50 --XYZ=-20:-20:-20"
slice-0: &slice-0
    Slurm: ./SLURM/blender/one.sbatch
    python: ./PYTHON/BLENDER/slices.py
    args: "{OUT}/png {PNG_FILES} -b {BLEND} {BLOCK}"
    Inputs:
        PNG_FILES: "-f %d/*.stl -l {ID-A}" 
        BLOCK: "--vox={XYZ_VOX} --VOL=50:50:50 --XYZ=-20:-20:-20"
scroll-0: &scroll-0
    Slurm: ./SLURM/blender/one.sbatch
    python: ./PYTHON/BLENDER/scroll.py
    args: "-b {BLEND} {Z_RANGE} {Z_RATE}"
    Inputs:
        Z_RANGE: "--VOL={XYZ_VOL} --zspan=100:801"
        Z_RATE: "--zps=100 --fps=24"
render-0: &render-0
    Runs: 10
    Slurm: ./SLURM/blender/many.sbatch
    python: ./PYTHON/BLENDER/render.py
    args: "-o {RENDER} -b {BLEND}"
########
# Command logic
logic:
    - &scene
      <<: *slice-0
      Needs:
        - <<: *block-0
scene:
    - &scene-new
      <<: *del-blend
      For:
        - *scene
scroll:
    - &scroll-scene
      <<: *scroll-0
      Needs:
        - *scene-new 
render:
    - &render-scroll
      <<: *render-0
      Needs:
        - *scroll-0
    - &render-scene
      <<: *render-0
      Needs:
        - *scroll-scene
########
# Commands
bash:
    Needs:
       - *block-0
       - *slice-0
       - *scroll-0
       - <<: *render-0
         Runs: 1
    Constants:
        NAME: bash_render
Main:
    <<: *del-logs
    For:
        - *render-scene
Default:
    Workdir: "git rev-parse --show-toplevel"
    Exports: [python, args]
    Flags: [partition]
    partition: holyseasgpu
    Constants:
        OUT: ./DATA/bfly_1soma
        XYZ_VOL: "50:50:50"
        XYZ_VOX: "32:32:4"
        TODAY: "2017_12_08"
        ID-A: "617637" 
        NAME: demo_render
    Inputs:
        BLEND: "./BLENDER/{TODAY}/{NAME}.blend"
        RENDER: "./RENDER/{TODAY}/{NAME}"
        LOG: "./LOGS/{TODAY}/{NAME}"
    Logs: "{LOG}"
