# slyml.py v2.1
#
stack-1: &stack-1
    Sync: 30
    Runs: 429
    Slurm: ./SLURM/many_z.sbatch
    python: ./PYTHON/scripts/sides.py
    args: "{PNG}/{ID} {EM_H5} {ID_H5} -i {ID} {HILITE}"
    Inputs:
        ID: "{ID-A}"
        HILITE: "-a z -g 5 -o 0.25"
stl-1: &stl-1
    Exports: [python, args]
    Slurm: ./SLURM/one.sbatch
    python: ./PYTHON/all_stl.py
    args: "--xyz -b 1 -l {ID} {ID_H5} {OUT}"
    Inputs:
        ID: "{ID-A}"
        HILITE: "-a z -g 5 -o 0.25"
del-log: &del-log
    Bash: true
    Exports: [args]
    Slurm: ./SLURM/bash/one.sbatch
    args: 'rm {LOG}*'
########
# For blender
del-blend: &del-blend
    <<: *del-log
    args: 'rm {BLEND}*'
light: &light
    Slurm: ./SLURM/blender/one.sbatch
    python: ./PYTHON/BLENDER/lights.py
    args: "-b {BLEND}"
sub-1: &sub-1
    Slurm: ./SLURM/blender/one.sbatch
    python: ./PYTHON/BLENDER/import.py
    args: "{OUT}/stl {STL_FILES} -b {BLEND} {BLOCK}"
    Inputs:
        STL_FILES: "-f %d/*.stl -l {ID-A}" 
        BLOCK: "--vox={XYZ_VOX} --VOL=50:50:50 --XYZ=-20:-20:-20"
slice-1: &slice-1
    Slurm: ./SLURM/blender/one.sbatch
    python: ./PYTHON/BLENDER/slices.py
    args: "{PNG} {PNG_FILES} -b {BLEND} {BLOCK}"
    Inputs:
        PNG_FILES: "-f %d/*.stl -l {ID-A}" 
        BLOCK: "--vox={XYZ_VOX} --VOL=50:50:50 --XYZ=-20:-20:-20"
scroll-1: &scroll-1
    Slurm: ./SLURM/blender/one.sbatch
    python: ./PYTHON/BLENDER/scroll.py
    args: "-b {BLEND} {Z_RANGE} {Z_RATE}"
    Inputs:
        Z_RANGE: "--VOL={XYZ_VOL} --zspan=100:801"
        Z_RATE: "--zps=100 --fps=24"
render-1: &render-1
    Runs: 10
    Slurm: ./SLURM/blender/many.sbatch
    python: ./PYTHON/BLENDER/render.py
    args: "-o {RENDER} -b {BLEND}"
########
# Command logic
Misc-1:
    - &make-data
      Needs:
        - <<: *stack-1
        - <<: *stl-1
    - &new-scene
      <<: *slice-1
      Needs:
        - <<: *sub-1
          Needs:
            - *del-blend
    - &new-scene-data
      <<: *slice-1
      Needs:
        - <<: *sub-1
          Needs:
            - *make-data
            - *del-blend
    - &new-scroll-scene
      <<: *scroll-1
      Needs:
         - *new-scene
    - &new-scroll-clean
      <<: *scroll-1
      Needs:
         - *new-scene-data
########
# Commands
test:
    <<: *render-1
    Needs:
        - *new-scroll-scene
Main:
    <<: *render-1
    Needs:
        - *new-scroll-clean
Default:
    Workdir: "git rev-parse --show-toplevel"
    Exports: [python, args]
    Constants:
        OUT_ROOT: /n/coxfs01/thejohnhoffer/R0/render
        IN_ROOT: /n/coxfs01/thejohnhoffer/R0/ids-2017-08-23_50um/images
        XYZ_VOL: "50:50:50"
        XYZ_VOX: "16:16:4"
        TODAY: "2017_11_30"
        NAME: parallel
        ID-A: "58146" 
    Inputs:
        ID_H5: "{IN_ROOT}/4_16_16_ids_all.h5"
        EM_H5: "{IN_ROOT}/4_16_16_raw_all.h5"
        OUT: "{OUT_ROOT}/{TODAY}/{NAME}"
        PNG: "{OUT_ROOT}/{TODAY}/{NAME}/png"
        BLEND: "./BLENDER/{TODAY}/{NAME}.blend"
        RENDER: "./RENDER/{TODAY}/{NAME}"
    Logs: "./LOGS/{TODAY}/{NAME}"
