Main: &main
    python: ./PYTHON/all_stl.py
    args: "-b 1 -l {LIST_IDS} {OUT}/id.h5 {OUT_NEW}"
    Constants: &main-constants
        SCALE: "2:5:5"
        LIST_IDS: "1:2:3"
        TODAY: "2017_11_11"
        NAME: Auguest_100/2_5_5
        BOSS: /n/coxfs01/leek/results/2017-08-23_100um_cube/88_88_14
    Needs: &main-needs
        - python: ./PYTHON/conversion/tif2hd.py
          args: "{OUT}/tif {OUT}/id.h5"
          Needs:
            - python: ./PYTHON/conversion/boss2stack.py
              args: "{BOSS_IDS} -o {OUT}/tif -s {SCALE} -f tif"
              Slurm: ./SLURM/many.sbatch
              Runs: 30
              Inputs:
                  BOSS_IDS: "{BOSS}/boss/final-segmentation/boss.json"
bfly_1soma:
    <<: *main
    Needs: []
    Constants:
        <<: *main-constants
        NEW: 'bfly_1soma'
        LIST_IDS: "58146"
# Failed Experiment 2017-11-15
# all_counts.py useless if only one block!!
fail-top5:
    <<: *main
    args: "-b 1 -d 1 -n 5 {OUT}/id.h5 {OUT_NEW}"
    Constants:
        <<: *main-constants
        NEW: 'top5'
    Needs:
        - python: ./PYTHON/all_counts.py
          args: "-b 1 -d 0 {OUT}/id.h5 {OUT_NEW}"
        - python: ./PYTHON/all_counts.py
          args: "-b 1 -d 1 {OUT}/id.h5 {OUT_NEW}"
    args: "-b 1 -d 1 -n 5 {OUT}/id.h5 {OUT_NEW}"
Default:
    Constants:
        OUT_ROOT: /n/coxfs01/thejohnhoffer/R0/render
        NEW: 'main'
    Inputs:
        OUT: "{OUT_ROOT}/{TODAY}/{NAME}"
        OUT_NEW: "{OUT_ROOT}/{TODAY}/{NAME}/{NEW}"
    Workdir: "git rev-parse --show-toplevel"
    Logs: "./LOGS/{TODAY}/{NAME}/{NEW}"
    Slurm: ./SLURM/one.sbatch
    Exports: [python, args]
