# slyml.py v2.2
#
Misc:
    - &mesh_json-0
      Slurm: ./SLURM/one.sbatch
      python: ./PYTHON/json_index.py
      args: "{OUT}/{3D}/pre"
    - &h5_mesh-0
      Slurm: ./SLURM/many.sbatch
      python: ./PYTHON/all_stl.py
      args: "{OUT}/id.h5 {OUT}/{3D} {MESH_FMT} -f %d:{MESH_RES} -b {N_BOX} -l {LIST}"
      Runs: "{N_BOX}**3"
    - &tif_mojo-id
      Slurm: ./SLURM/many.sbatch
      python: ./PYTHON/conversion/tif2mojo.py
      args: "{TIF_ID} --id -o {MOJO_OUT}"
      Runs: "{Z_RUN}"
    - &tif_mojo-em
      Slurm: ./SLURM/many.sbatch
      python: ./PYTHON/conversion/tif2mojo.py
      args: "{TIF_EM} --em -o {MOJO_OUT}"
      Runs: "{Z_RUN}"
    - &tif_h5-id
      Slurm: ./SLURM/one.sbatch
      python: ./PYTHON/conversion/tif2hd.py
      args: "{TIF_ID} {OUT}/id.h5"
    - &tif_h5-em
      Slurm: ./SLURM/one.sbatch
      python: ./PYTHON/conversion/tif2hd.py
      args: "{TIF_EM} {OUT}/em.h5"
kai_mojo: &kai_mojo
    - *tif_mojo-em
    - *tif_mojo-id
kai_mesh: &kai_mesh
    <<: *h5_mesh-0
    For: *mesh_json-0
    Needs: *tif_h5-id
    Constants:
        N_BOX: 5
        MESH_RES: 0
        3D: 'nrn_v1'
        LIST: "1-2"
kai:
    Needs:
        - *kai_mojo
        - <<: *kai_mesh    
          Inputs: {LIST: "1-255"}
Default:
    Constants:
        TIF_EM: /n/coxfs01/thejohnhoffer/JWR/fromKai/2018_01_17/em
        TIF_ID: /n/coxfs01/thejohnhoffer/JWR/fromKai/2018_01_17/id
        OUT_ROOT: /n/coxfs01/thejohnhoffer/JWR/ng_mesh/
        MOJO_ROOT: /n/coxfs01/thejohnhoffer/mojo/
        MESH_FMT: "--pre --xyz"
        TODAY: "2018_01_17"
        NAME: kai_v0
        Z_RUN: 50
    Inputs:
        OUT: "{OUT_ROOT}/{TODAY}/{NAME}"
        MOJO_OUT: "{MOJO_ROOT}/{TODAY}/{NAME}"
    Workdir: "git rev-parse --show-toplevel"
    Logs: "./LOGS/{TODAY}/{NAME}"
    Exports: [python, args]
    Flags: [partition]
    partition: holyseasgpu
