# slyml.py v2.2
#
Misc:
    - &stl_x3d-0
      Slurm: ./SLURM/blender/one.sbatch
      python: ./PYTHON/BLENDER/import.py
      args: "-r {MESH_RUN} -V {ANISO} -R {EM_Z}:{EM_XY} -I {ID_Z}:{ID_XY} {WEB}"  
      Inputs:
          WEB: "-l {LIST} -w {WWW} {OUT}/em.h5 {OUT}/tif/em {OUT}/{3D}"
    - &mesh_json-0
      Slurm: ./SLURM/one.sbatch
      python: ./PYTHON/json_index.py
      args: "{OUT}/{3D}/pre"
    - &h5_mesh-0
      Slurm: ./SLURM/many.sbatch
      python: ./PYTHON/all_stl.py
      args: "{OUT}/id.h5 {OUT}/{3D} {MESH_FMT} -f %d:{MESH_RES} -b {N_BOX} -l {LIST}"
      Runs: "{N_BOX}**3"
    - &tif_h5-0
      Slurm: ./SLURM/one.sbatch
      python: ./PYTHON/conversion/tif2hd.py
    - &boss_tif-0
      python: ./PYTHON/conversion/boss2stack.py
      Slurm: ./SLURM/many.sbatch
      Runs: 40
    - &boss_h5-id
      <<: *tif_h5-0
      args: "{OUT}/tif/id {OUT}/id.h5"
      Inputs:
          CROP: "-s {ID_Z}:{ID_YX}:{ID_YX}"
      Needs:
          <<: *boss_tif-0 
          args: "{BOSS_ID} -o {OUT}/tif/id {CROP} {ID_OFF} -f tif"
    - &boss_h5-em
      <<: *tif_h5-0
      args: "{OUT}/tif/em {OUT}/em.h5"
      Inputs:
          CROP: "-s {EM_Z}:{EM_YX}:{EM_YX}"
      Needs:
          <<: *boss_tif-0 
          args: "{BOSS_EM} -o {OUT}/tif/em {CROP} -f tif"
konsta_in: &konsta_in-0
    <<: *h5_mesh-0
    args: "{ID_H5} {OUT}/{3D} {MESH_FMT} -f %d:{MESH_RES} -b {N_BOX} -l {LIST}"
    Constants:
        ID_Z: 0
        EM_Z: 0
        ID_YX: 0
        EM_YX: 0
        N_BOX: 3
        MESH_RES: 0
        NAME: 'konsta'
        TODAY: "2018_01_10"
        ID_OFF: "-d 0:0:0"
        ID_H5: /n/coxfs01/kdmitriev/neuronseg/rhoana/microns-seg-450-test.h5
        3D: 'nrn_in_v1'
        LIST: "499-500"
    For: *mesh_json-0
konsta_out: &konsta_out-0
    <<: *h5_mesh-0
    args: "{ID_H5} {OUT}/{3D} {MESH_FMT} -f %d:{MESH_RES} -b {N_BOX} -l {LIST}"
    Constants:
        ID_Z: 0
        EM_Z: 0
        ID_YX: 0
        EM_YX: 0
        N_BOX: 3
        MESH_RES: 0
        NAME: 'konsta'
        TODAY: "2018_01_10"
        ID_OFF: "-d 0:0:0"
        ID_H5: /n/coxfs01/kdmitriev/corrected_results/v1/corrected_labels.h5
        3D: 'nrn_out_v1'
        LIST: "499-500"
    For: *mesh_json-0
konsta_all:
    Needs:
        - <<: *konsta_in-0    
          Inputs: {LIST: "1-2000"}
        - <<: *konsta_in-0    
          Inputs: {LIST: "2000-4000"}
        - <<: *konsta_in-0    
          Inputs: {LIST: "4000-6000"}
        - <<: *konsta_out-0    
          Inputs: {LIST: "1-2000"}
        - <<: *konsta_out-0    
          Inputs: {LIST: "2000-4000"}
        - <<: *konsta_out-0    
          Inputs: {LIST: "4000-6000"}
    Constants:
        TODAY: "2018_01_11"
        NAME: konsta_all
syn_10e4:
    <<: *h5_mesh-0
    Constants:
        ID_Z: 3
        EM_Z: 3
        ID_YX: 5
        EM_YX: 5
        N_BOX: 2
        MESH_RES: 0
        TODAY: "2018_01_10"
        NAME: 'nm_zx_120_128'
        ID_OFF: "-d 0:1024:1024"
        3D: 'syn_10e4'
        LIST: "1-10"
    #Needs: *boss_h5-id
    For: *mesh_json-0
Default:
    Constants:
        BOSS_EM: /n/coxfs01/leek/data/JWR_boss-no-duplicates.json
        BOSS_ID: /n/coxfs01/leek/results/2017-12-04_100um-cube/boss/final-synapse-segmentation/boss.json
        OUT_ROOT: /n/coxfs01/thejohnhoffer/JWR/ng_mesh/
        MESH_FMT: "--pre --xyz"
        MESH_RUN: 10
        ANISO: 7.5
        WWW: ./WWW
    Inputs:
        OUT: "{OUT_ROOT}/{TODAY}/{NAME}"
    Workdir: "git rev-parse --show-toplevel"
    Logs: "./LOGS/{TODAY}/{NAME}"
    Exports: [python, args]
    Flags: [partition]
    partition: general
