# slyml.py v2.2
#
Misc:
    - &stl_x3d-0
      Slurm: ./SLURM/blender/one.sbatch
      python: ./PYTHON/BLENDER/import.py
      args: "-r {MESH_RUN} -V {ANISO} -R {EM_Z}:{EM_XY} -I {ID_Z}:{ID_XY} {WEB}"  
      Inputs:
          WEB: "-l {LIST} -w {WWW} {OUT}/em.h5 {OUT}/tif/em {OUT}/{3D}"
    - &h5_pre-0
      Slurm: ./SLURM/many.sbatch
      python: ./PYTHON/all_stl.py
      args: "{OUT}/id.h5 {OUT}/{3D} --pre --xyz -b {N_BOX} -l {LIST}"
      Runs: "{N_BOX}**3"
    - &tif_h5-0
      Slurm: ./SLURM/one.sbatch
      python: ./PYTHON//tif2hd.py
    - &boss_tif-0
      python: ./PYTHON/conversion/boss2stack.py
      Slurm: ./SLURM/many.sbatch
      Runs: 40
    - &boss_h5-id
      Needs:
          <<: *tif_h5-0
          args: "{OUT}/tif/id {OUT}/id.h5"
          Inputs:
              CROP: "-s {ID_Z}:{ID_YX}:{ID_YX}"
          Needs:
              <<: *boss_tif-0 
              args: "{BOSS_ID} -o {OUT}/tif/id {CROP} {ID_OFF} -f tif"
    - &boss_h5-em
      Needs:
          <<: *tif_h5-0
          args: "{OUT}/tif/em {OUT}/em.h5"
          Inputs:
              CROP: "-s {EM_Z}:{EM_YX}:{EM_YX}"
          Needs:
              <<: *boss_tif-0 
              args: "{BOSS_EM} -o {OUT}/tif/em {CROP} -f tif"
pre_120nm: &pre_120nm
    <<: *h5_pre-0
    Constants:
        ID_Z: 3
        EM_Z: 3
        ID_YX: 5
        EM_YX: 5
        3D: 'pre'
        N_BOX: 2
        TODAY: "2018_01_10"
        NAME: 'nm_zx_120_128'
        ID_OFF: "-d 0:1024:1024"
        LIST: "1:2:3"
    Needs:
        <<: *h5_pre-0
        Needs: *boss_h5-id
Default:
    Constants:
        BOSS_EM: /n/coxfs01/leek/data/JWR_boss-no-duplicates.json
        BOSS_ID: /n/coxfs01/leek/results/2017-12-04_100um-cube/boss/final-synapse-segmentation/boss.json
        OUT_ROOT: /n/coxfs01/thejohnhoffer/JWR/syn_1_10e4/
        MESH_RUN: 10
        ANISO: 7.5
        WWW: ./WWW
    Inputs:
        OUT: "{OUT_ROOT}/{TODAY}/{NAME}"
    Logs: "./LOGS/{TODAY}/{NAME}"
    Exports: [python, args]
    Flags: [partition]
    partition: general
